// Realistic Mock Data Generator for DNA SuperKit Testing

export function generateSampleKit1Text(): string {
  const lines: string[] = [
    "# AncestryDNA raw data download",
    "# This file was generated by Ancestry.com for demonstration/testing",
    "# Build: GRCh37 (hg19)",
    "# Format: rsid\tchromosome\tposition\tallele1\tallele2",
    "rsid\tchromosome\tposition\tallele1\tallele2"
  ];

  const chromosomes = ["1", "2", "3", "6", "11", "17", "22", "23", "24", "25"];

  for (let cIdx = 0; cIdx < chromosomes.length; cIdx++) {
    const chr = chromosomes[cIdx];
    const snpCount = cIdx === 0 ? 40 : 25;

    for (let i = 0; i < snpCount; i++) {
      const pos = 100000 + i * 500;
      const rsid = `rs${1000000 + cIdx * 1000 + i}`;
      
      let a1 = "A";
      let a2 = "T";

      if (i % 5 === 0) {
        // Gap Fill test case (Kit 1 has no-call 00)
        a1 = "0";
        a2 = "0";
      } else if (i % 7 === 0) {
        // Discordant test case (Kit 1 has AA, Kit 2 will have GG)
        a1 = "A";
        a2 = "A";
      }

      lines.push(`${rsid}\t${chr}\t${pos}\t${a1}\t${a2}`);
    }
  }

  // Add 15 unique Kit 1 SNPs
  for (let i = 0; i < 15; i++) {
    lines.push(`rs9900${i}\t1\t${900000 + i * 300}\tG\tT`);
  }

  return lines.join("\n");
}

export function generateSampleKit2Text(): string {
  const lines: string[] = [
    "# 23andMe raw data download",
    "# This data file was generated by 23andMe for testing",
    "# Assembly: GRCh37",
    "# rsid\tchromosome\tposition\tgenotype"
  ];

  const chromosomes = ["1", "2", "3", "6", "11", "17", "22", "23", "24", "25"];

  for (let cIdx = 0; cIdx < chromosomes.length; cIdx++) {
    const chr = chromosomes[cIdx];
    const chrLabel = chr === "23" ? "X" : chr === "24" ? "Y" : chr === "25" ? "MT" : chr;
    const snpCount = cIdx === 0 ? 40 : 25;

    for (let i = 0; i < snpCount; i++) {
      const pos = 100000 + i * 500; // Same exact position as Kit 1!
      const rsid = i % 4 === 0 ? `i${400000 + cIdx * 100 + i}` : `rs${1000000 + cIdx * 1000 + i}`;
      
      let genotype = "AT";

      if (i % 5 === 0) {
        // Gap Fill case (Kit 1 is 00, Kit 2 is CG)
        genotype = "CG";
      } else if (i % 7 === 0) {
        // Discordant case (Kit 1 is AA, Kit 2 is GG)
        genotype = "GG";
      }

      lines.push(`${rsid}\t${chrLabel}\t${pos}\t${genotype}`);
    }
  }

  // Add 20 unique Kit 2 SNPs
  for (let i = 0; i < 20; i++) {
    lines.push(`rs8800${i}\t2\t${950000 + i * 300}\tAC`);
  }

  return lines.join("\n");
}
